name: recursive_reasoning.trm_diffusion@TinyRecursiveReasoningModel_Diffusion
loss:
  name: losses@DiffusionLossHead
  loss_type: stablemax_cross_entropy

halt_exploration_prob: 0.0
halt_max_steps: 16

H_cycles: 3
L_cycles: 4

H_layers: 0
L_layers: 2

hidden_size: 512
num_heads: 8
expansion: 4

puzzle_emb_ndim: ${.hidden_size}

pos_encodings: rope
forward_dtype: bfloat16

mlp_t: False
puzzle_emb_len: 16
no_ACT_continue: True

task: maze
mask_schedule_kind: cosine
corrupt_rate: 0.1
base_loss_weight: 0.1
n_infer_steps: 0  # 0 means use halt_max_steps
